global using System.IO.Abstractions;
global using Erdmier.ZooTycoonLauncher.Application.Common.Abstractions;
global using Erdmier.ZooTycoonLauncher.Domain.Installations;
global using Erdmier.ZooTycoonLauncher.Domain.IniSnapshots;
global using Erdmier.ZooTycoonLauncher.Domain.Settings;
global using JetBrains.Annotations;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
