// <auto-generated />
using System;
using Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Launcher;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Launcher.Migrations
{
    [DbContext(typeof(LauncherDbContext))]
    partial class LauncherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.Installations.GameInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasExe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIni")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("GameInstallations", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.Settings.LauncherSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAfterGameLaunch")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultInstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LauncherStartupPreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.ToTable("LauncherSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_LauncherSettings_SingletonRow", "\"Id\" = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
