<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Erdmier.ZooTycoonLauncher.Application.Tests.Unit</RootNamespace>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Source\Erdmier.ZooTycoonLauncher.Application\Erdmier.ZooTycoonLauncher.Application.csproj" />
    </ItemGroup>
</Project>
