<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <RootNamespace>Erdmier.ZooTycoonLauncher.Desktop</RootNamespace>
        <AssemblyName>Erdmier.ZooTycoonLauncher.Desktop</AssemblyName>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Classic.Avalonia.Theme" />
        <PackageReference Include="Classic.Avalonia.Theme.DataGrid" />
        <PackageReference Include="Classic.Avalonia.Theme.Dock" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Erdmier.ZooTycoonLauncher.Application\Erdmier.ZooTycoonLauncher.Application.csproj" />
        <ProjectReference Include="..\Erdmier.ZooTycoonLauncher.Infrastructure\Erdmier.ZooTycoonLauncher.Infrastructure.csproj" />
    </ItemGroup>
</Project>
