// <auto-generated />
using System;
using Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Installation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Installation.Migrations
{
    [DbContext(typeof(InstallationDbContext))]
    [Migration("20260528001444_InitialInstallationSchema")]
    partial class InitialInstallationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StructureBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Section", "Key")
                        .IsUnique();

                    b.ToTable("IniValues", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniValue", b =>
                {
                    b.HasOne("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", null)
                        .WithMany("Values")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
