// <auto-generated />
using System;
using Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Installation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erdmier.ZooTycoonLauncher.Infrastructure.Persistence.Installation.Migrations
{
    [DbContext(typeof(InstallationDbContext))]
    [Migration("20260528001444_InitialInstallationSchema")]
    partial class InitialInstallationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StructureBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Snapshots", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Section", "Key")
                        .IsUnique();

                    b.ToTable("IniValues", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.Installations.GameInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasExe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIni")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPlayedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("GameInstallations", (string)null);
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.Settings.LauncherSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CloseAfterGameLaunch")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultInstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LauncherStartupPreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.HasKey("Id");

                    b.ToTable("LauncherSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_LauncherSettings_SingletonRow", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniValue", b =>
                {
                    b.HasOne("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", null)
                        .WithMany("Values")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erdmier.ZooTycoonLauncher.Domain.IniSnapshots.IniSnapshot", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
